version: '3.9'
services:
  dns-resolver:
    build:
      context: .
      dockerfile: resolver/Dockerfile
    ports:
      - "53:53/udp"
  root-server:
    build:
      context: .
      dockerfile: root-server/Dockerfile
    ports:
      - "5301:53/udp"