# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod tidy

    - name: Build Resolver
      run: go build -o build/app ./resolver/main.go
    
    - name: Build Root Server
      run: go build -o build/app ./root-server/main.go
    
    - name: Build TLD Server
      run: go build -o build/app ./tld-server/main.go
    
    - name: Build Auth Server
      run: go build -o build/app ./auth-server/main.go
      
    - name: Run tests
      run: go test -v ./...
